services:
  db:
    image: mysql:8.0.36
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
#      MYSQL_USER: 'root'
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_HOST: ''
    networks:
      - openlxp

  app:
    container_name: openlxp-xds
    image: registry1.dso.mil/ironbank/adl-ousd/ecc-openlxp/ecc-openlxp-xds
    ports:
      - "8100:8020"
    command: >
      sh -c ". /tmp/app/start-app.sh"
    environment:
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      COOKIE_NAME: "${COOKIE_NAME}"
      COOKIE_VALUE: "${COOKIE_VALUE}"
      CSRF_COOKIE_DOMAIN: "${CSRF_COOKIE_DOMAIN}"
      CSRF_TRUSTED_ORIGINS: "${CSRF_TRUSTED_ORIGINS}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
      ENTITY_ID: "${ENTITY_ID}"
      LOGIN_REDIRECT_URL: "${LOGIN_REDIRECT_URL}"
      LOG_PATH: "${LOG_PATH}"
      # P1PS_DOMAIN: "${P1PS_DOMAIN}"
      SECRET_KEY_VAL: "${SECRET_KEY_VAL}"
      SP_PUBLIC_CERT: "${SP_PUBLIC_CERT}"
      SP_PRIVATE_KEY: "${SP_PRIVATE_KEY}"
      TEAM_ID: "${TEAM_ID}"
      TEAM_TOKEN: "${TEAM_TOKEN}"
    volumes:
      - ./app:/tmp/app/openlxp-xds
    depends_on:
      - db
    networks:
      - openlxp

  nginx:
    image: nginx:latest
    ports:
      - "8001:8020"
    volumes:
      - ./nginx.default:/etc/nginx/conf.d/default.conf
      - ./app:/tmp/app/openlxp-xds
    restart: always
    depends_on:
      - app
    networks:
      - openlxp

networks:
  openlxp:
    external: true
