version: "3"

services:
  db:
    image: mysql:8.0.36
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
#      MYSQL_USER: 'root'
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_HOST: ''
    networks:
      - openlxp

  app:
    container_name: openlxp-xds
    build:
      context: .
    ports:
      - "8100:8020"
    command: >
      sh -c ". /opt/app/start-app.sh"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
      CSRF_COOKIE_DOMAIN: "${CSRF_COOKIE_DOMAIN}"
      CSRF_TRUSTED_ORIGINS: "${CSRF_TRUSTED_ORIGINS}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USER: "${DB_USER}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      ENTITY_ID: "${ENTITY_ID}"
      LOG_PATH: "${LOG_PATH}"
      LOGIN_REDIRECT_URL: "${LOGIN_REDIRECT_URL}"
      REQUESTS_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
      SECRET_KEY_VAL: "${SECRET_KEY_VAL}"
      SP_PRIVATE_KEY: "${SP_PRIVATE_KEY}"
      SP_PUBLIC_CERT: "${SP_PUBLIC_CERT}"
    volumes:
      - ./app:/opt/app/openlxp-xds
    depends_on:
      - db
    networks:
      - openlxp

networks:
  openlxp:
    external: true
