version: "3"

services:
  db:
    image: mysql:8.4
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
#      MYSQL_USER: 'root'
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_HOST: ''
    networks:
      - openlxp

  app:
    container_name: openlxp-xds
    build:
      context: .
    ports:
      - "8100:8020"
    command: >
      sh -c ". /opt/app/start-app.sh"
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      REQUESTS_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
      AWS_CA_BUNDLE: '/etc/ssl/certs/ca-certificates.crt'
      SECRET_KEY_VAL: "${SECRET_KEY_VAL}"
      LOG_PATH: "${LOG_PATH}"
      ENTITY_ID: "${ENTITY_ID}"
      SP_PUBLIC_CERT: "${SP_PUBLIC_CERT}"
      SP_PRIVATE_KEY: "${SP_PRIVATE_KEY}"
      BAD_HOST: "${BAD_HOST}"
      OVERIDE_HOST: "${OVERIDE_HOST}"
      LOGIN_REDIRECT_URL: "${LOGIN_REDIRECT_URL}"
    volumes:
      - ./app:/opt/app/openlxp-xds
    depends_on:
      - db
    networks:
      - openlxp

networks:
  openlxp:
    external: true
