# Generated by Django 3.1.7 on 2021-03-30 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XDSConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_xis_metadata_api', models.CharField(help_text='Enter the XIS api endpoint to query metadata', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='XDSUIConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_results_per_page', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, 'results per page                             should be at least 1')])),
                ('xds_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.xdsconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter the display name of the field to filter on', max_length=200)),
                ('field_name', models.CharField(help_text='Enter the metadata field name as displayed in Elasticsearch             e.g. course.title', max_length=200)),
                ('filter_type', models.CharField(choices=[('terms', 'Checkbox')], default='terms', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('xds_ui_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.xdsuiconfiguration')),
            ],
        ),
    ]
