# Generated by Django 3.1.8 on 2021-04-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailhighlight',
            name='highlight_icon',
            field=models.CharField(choices=[('clock', 'clock'), ('hourglass', 'hourglass'), ('user', 'user'), ('multi_users', 'multi_users'), ('location', 'location'), ('calendar', 'calendar')], default='user', max_length=200),
        ),
    ]
