# Generated by Django 3.1.8 on 2021-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xdsuiconfiguration',
            name='course_img_fallback',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
