# Generated by Django 3.1.7 on 2021-04-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSortOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Enter the display name of the sorting option', max_length=200)),
                ('field_name', models.CharField(help_text='Enter the metadata field name as displayed in Elasticsearch             e.g. course.title', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('xds_ui_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.xdsuiconfiguration')),
            ],
        ),
    ]
