# Generated by Django 3.1.8 on 2021-04-14 14:57

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_xdsuiconfiguration_course_img_fallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetailHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('display_name', models.CharField(help_text='Enter the display name of the sorting option', max_length=200)),
                ('field_name', models.CharField(help_text='Enter the metadata field name as displayed in Elasticsearch e.g. course.title', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('highlight_icon', models.CharField(choices=[('clock', 'clock'), ('hourglass', 'hourglass'), ('user', 'user'), ('multi-users', 'multi-users'), ('location', 'location'), ('calendar', 'calendar')], default='user', max_length=200)),
                ('xds_ui_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_highlights', to='core.xdsuiconfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
