# Generated by Django 3.1.8 on 2021-04-14 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coursedetailhighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetailhighlight',
            name='rank',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'rank shoud be at least 1')]),
        ),
    ]
