# Generated by Django 3.1.8 on 2021-05-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210427_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='xdsconfiguration',
            name='target_xis_composite_ledger_api',
            field=models.CharField(default='http://localhost:8080/api/composite-ledger/', help_text='Enter the XIS api endpoint to query composite ledger data', max_length=200),
        ),
    ]
