# Generated by Django 3.1.8 on 2021-05-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_xdsconfiguration_target_xis_composite_ledger_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xdsconfiguration',
            name='target_xis_composite_ledger_api',
            field=models.CharField(default='http://localhost:8080/api/metadata/', help_text='Enter the XIS api endpoint to query composite ledger data', max_length=200),
        ),
    ]
