# Generated by Django 3.1.8 on 2021-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210504_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xdsconfiguration',
            name='target_xis_composite_ledger_api',
        ),
        migrations.AlterField(
            model_name='xdsconfiguration',
            name='target_xis_metadata_api',
            field=models.CharField(default='http://localhost:8080/api/metadata/', help_text='Enter the XIS api endpoint to query metadata', max_length=200),
        ),
    ]
