# Generated by Django 3.1.12 on 2021-06-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_courseinformationmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformationmapping',
            name='course_title',
            field=models.CharField(help_text='Enter the title of the coursefound in the elasticsearch', max_length=200),
        ),
        migrations.AlterField(
            model_name='courseinformationmapping',
            name='xds_ui_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_information', to='core.xdsuiconfiguration'),
        ),
    ]
