name: Docker CD

on:
  push:
    branches: 
      - main
      - micson-test-WIP
  pull_request:
    branches: 
      - main
      - micson-test-WIP
jobs:
  code-test:
    name: Code Test
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Checkout private repository
      uses: actions/checkout@v1
      with:
        repository: openlxp/openlxp-private
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Generate Coverage Report
      run: |
        pip install pytest
        pip install pytest-cov
        pwd
        docker network create openlxp
        docker-compose --env-file /openlxp-private/openlxp-xds-env/.env run app sh -c "python manage.py waitdb && coverage run manage.py test --tag=unit && flake8 && coverage report && coverage report --fail-under=80"
# Commenting this step for now. 
#    - name: Upload Coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        fail_ci_if_error: true
#        path_to_write_report: ./coverage/codecov_report.txt
        
  build:
    needs: code-test
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Docker login
      env:
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker build
      run: |
       docker build . -t openlxp/openlxp-xds
    - name: Push Image
      run: |
        docker push openlxp/openlxp-xds
